#include <string>

void rd(int &x);
void rd(long long &x);
void rd(unsigned &x);
void rd(unsigned long long &x);
void rd(double &x);
void rd(float &x);
void rd(char &c);
int rd(char c[]);
void rd(std::string &x);
int rdLine(char c[]);
int rdLine(std::string &x);
void wt_L(const char c[]);
void wt_L(std::string &x);
int writerDigit_double();
void writerDigit_double(int d);
void wt_L(char a);
void wt_L(float x);
void wt_L(double x);
void wt_L(int x);
void wt_L(unsigned x);
void wt_L(long long x);
void wt_L(unsigned long long x);
void dbwt_L(const char c[]);
void dbwt_L(std::string &x);
void dbwt_L(char a);
void dbwt_L(float x);
void dbwt_L(double x);
void dbwt_L(int x);
void dbwt_L(unsigned x);
void dbwt_L(long long x);
void dbwt_L(unsigned long long x);
void rdFile(char *buffer, bool efficient );